package entity;

import javax.persistence.*;
import java.time.LocalDate;

/**
 * Represents a librarian in the library system.
 * A Librarian is a specialized type of User, modeled as a separate table with a one-to-one relationship to the User table.
 */

@Entity
@Table(name = "Librarians")
public class Librarian {

    /**
     * Unique identifier for the librarian.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The associated user for this librarian.
     * Each librarian corresponds to exactly one user.
     */
    @OneToOne
    @JoinColumn(name = "user_id", unique = true)
    private User user;
    /**
     * Represents employment date of Librarian.
     */
    private LocalDate employmentDate;

    /**
     * Represents position of Librarian.
     */
    private String position;

    /**
     * Default constructor for JPA.
     */
    public Librarian() { }

    /**
     * Constructs a new Librarian instance with the given details.
     *
     * @param user           the user associated with this librarian
     * @param employmentDate the date the librarian was employed
     * @param position       the job position of the librarian
     */
    public Librarian(User user, LocalDate employmentDate, String position) {
        this.user = user;
        this.employmentDate = employmentDate;
        this.position = position;
    }

    // ---------------------------------------------------------------------getters
    /**
     * Gets the unique identifier of the librarian.
     * @return the ID of the librarian
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the user associated with this librarian.
     * @return the {@link User} entity linked to this librarian
     */
    public User getUser() {
        return user;
    }

    /**
     * Gets the position of the librarian.
     * @return the job position of the librarian
     */
    public String getPosition() {
        return position;
    }

    // ---------------------------------------------------------------------setters
    /**
     * Sets the job position of the librarian.
     *
     * @param position the job position to set
     */
    public void setPosition(String position) {
        this.position = position;
    }
}
