package entity;

import javax.persistence.*;

/**
 * Represents a publisher entity in the library system.
 * Publishers can be associated with books as their publishing entity.
 */
@Entity
@Table(name = "Publishers")
public class Publisher {

    /**
     * Unique identifier for the publisher.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Represents name of Publisher
     */
    private String name;

    /**
     * Represents address of Publisher.
     */
    private String address;

    /**
     * Represents phone number of Publisher.
     */
    private String phoneNumber;

    /**
     * Default constructor for JPA.
     */
    public Publisher() {}

    /**
     * Constructs a new Publisher instance with the given details.
     *
     * @param name        the name of the publisher
     * @param address     the address of the publisher
     * @param phoneNumber the phone number of the publisher
     */
    public Publisher(String name, String address, String phoneNumber) {
        this.name = name;
        this.address = address;
        this.phoneNumber = phoneNumber;
    }
    //--------------------------------------------------------------getters
    /**
     * Gets the unique identifier of the publisher.
     *
     * @return the ID of the publisher
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the name of the publisher.
     *
     * @return the name of the publisher
     */
    public String getName() {
        return name;
    }
}